<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Archive uploaded, work in progress' => 'Архив загружен, ведется обработка',
    'Archive will be downloaded soon' => 'Загрузка архива начнется через некоторое время',
    'Attachment deleted' => 'Вложение удалено',
    'Attachment updated' => 'Вложение сохранено',
    'Attachments' => 'Вложения',
    'Cannot delete attachment' => 'Не удалось удалить вложение',
    'Cannot store temp file' => 'Невозможно сохранить временный файл',
    'Cannot write file to storage' => 'Невозможно записать файл в хранилище',
    'Create page' => 'Создание страницы',
    'Documentation' => 'Документация',
    'Download documentation' => 'Скачать документацию',
    'Download wiki data' => 'Скачать данные справочника',
    'Error while setting export job' => 'Произошла ошибка при экспорте',
    'Export' => 'Экспорт',
    'Files can be attached to created pages only' => 'Файл можно добавить только к созданной странице',
    'Help' => 'Справка',
    'Import' => 'Импорт',
    'Import wiki data' => 'Импортировать данные справочника',
    'Nested pages' => 'Вложенные страницы',
    'Page #{id}' => 'Страница #{id}',
    'Page has related records and can not be deleted' => 'Страница имеет вложенные записи и не может быть удалена',
    'Page updated' => 'Страница сохранена',
    'Update attachment' => 'Редактирование вложения',
    'Update page' => 'Редактирование страницы',
    'PAGE_DELETE_WARNING' => 'Вы уверены, что хотите удалить эту страницу?',
    'PAGE_SUBPAGE_DELETE_WARNING' => 'Эта страница содержит дочерние страницы, которые также будут удалены! Вы уверены?',
];
