<?php

namespace common\helpers;

use \Yii;

/**
 * Class Countries
 * @package common\helpers
 * @todo записать массив по всем странам и всем кодам, пока самое простое
 */
abstract class Countries
{
	const ISO_3166_1_ALFA_2 = 1;

	protected static $allCountryCodes;
	protected static $allNumericCodes;

	protected static function iso3166_1_alfa_2()
	{
		return [
			'AF' => Yii::t('app/country', 'Afghanistan'),
			'AX' => Yii::t('app/country', 'Aland Islands'),
			'AL' => Yii::t('app/country', 'Albania'),
			'DZ' => Yii::t('app/country', 'Algeria'),
			'AS' => Yii::t('app/country', 'American Samoa'),
			'AD' => Yii::t('app/country', 'Andorra'),
			'AO' => Yii::t('app/country', 'Angola'),
			'AI' => Yii::t('app/country', 'Anguilla'),
			'AQ' => Yii::t('app/country', 'Antarctica'),
			'AG' => Yii::t('app/country', 'Antigua And Barbuda'),
			'AR' => Yii::t('app/country', 'Argentina'),
			'AM' => Yii::t('app/country', 'Armenia'),
			'AW' => Yii::t('app/country', 'Aruba'),
			'AU' => Yii::t('app/country', 'Australia'),
			'AT' => Yii::t('app/country', 'Austria'),
			'AZ' => Yii::t('app/country', 'Azerbaijan'),
			'BS' => Yii::t('app/country', 'Bahamas'),
			'BH' => Yii::t('app/country', 'Bahrain'),
			'BD' => Yii::t('app/country', 'Bangladesh'),
			'BB' => Yii::t('app/country', 'Barbados'),
			'BY' => Yii::t('app/country', 'Belarus'),
			'BE' => Yii::t('app/country', 'Belgium'),
			'BZ' => Yii::t('app/country', 'Belize'),
			'BJ' => Yii::t('app/country', 'Benin'),
			'BM' => Yii::t('app/country', 'Bermuda'),
			'BT' => Yii::t('app/country', 'Bhutan'),
			'BO' => Yii::t('app/country', 'Bolivia'),
			'BA' => Yii::t('app/country', 'Bosnia And Herzegovina'),
			'BW' => Yii::t('app/country', 'Botswana'),
			'BV' => Yii::t('app/country', 'Bouvet Island'),
			'BR' => Yii::t('app/country', 'Brazil'),
			'IO' => Yii::t('app/country', 'British Indian Ocean Territory'),
			'BN' => Yii::t('app/country', 'Brunei Darussalam'),
			'BG' => Yii::t('app/country', 'Bulgaria'),
			'BF' => Yii::t('app/country', 'Burkina Faso'),
			'BI' => Yii::t('app/country', 'Burundi'),
			'KH' => Yii::t('app/country', 'Cambodia'),
			'CM' => Yii::t('app/country', 'Cameroon'),
			'CA' => Yii::t('app/country', 'Canada'),
			'CV' => Yii::t('app/country', 'Cape Verde'),
			'KY' => Yii::t('app/country', 'Cayman Islands'),
			'CF' => Yii::t('app/country', 'Central African Republic'),
			'TD' => Yii::t('app/country', 'Chad'),
			'CL' => Yii::t('app/country', 'Chile'),
			'CN' => Yii::t('app/country', 'China'),
			'CX' => Yii::t('app/country', 'Christmas Island'),
			'CC' => Yii::t('app/country', 'Cocos (Keeling) Islands'),
			'CO' => Yii::t('app/country', 'Colombia'),
			'KM' => Yii::t('app/country', 'Comoros'),
			'CG' => Yii::t('app/country', 'Congo'),
			'CD' => Yii::t('app/country', 'Congo Democratic Republic'),
			'CK' => Yii::t('app/country', 'Cook Islands'),
			'CR' => Yii::t('app/country', 'Costa Rica'),
			'CI' => Yii::t('app/country', 'Cote D\'Ivoire'),
			'HR' => Yii::t('app/country', 'Croatia'),
			'CU' => Yii::t('app/country', 'Cuba'),
			'CY' => Yii::t('app/country', 'Cyprus'),
			'CZ' => Yii::t('app/country', 'Czech Republic'),
			'DK' => Yii::t('app/country', 'Denmark'),
			'DJ' => Yii::t('app/country', 'Djibouti'),
			'DM' => Yii::t('app/country', 'Dominica'),
			'DO' => Yii::t('app/country', 'Dominican Republic'),
			'EC' => Yii::t('app/country', 'Ecuador'),
			'EG' => Yii::t('app/country', 'Egypt'),
			'SV' => Yii::t('app/country', 'El Salvador'),
			'GQ' => Yii::t('app/country', 'Equatorial Guinea'),
			'ER' => Yii::t('app/country', 'Eritrea'),
			'EE' => Yii::t('app/country', 'Estonia'),
			'ET' => Yii::t('app/country', 'Ethiopia'),
			'FK' => Yii::t('app/country', 'Falkland Islands (Malvinas)'),
			'FO' => Yii::t('app/country', 'Faroe Islands'),
			'FJ' => Yii::t('app/country', 'Fiji'),
			'FI' => Yii::t('app/country', 'Finland'),
			'FR' => Yii::t('app/country', 'France'),
			'GF' => Yii::t('app/country', 'French Guiana'),
			'PF' => Yii::t('app/country', 'French Polynesia'),
			'TF' => Yii::t('app/country', 'French Southern Territories'),
			'GA' => Yii::t('app/country', 'Gabon'),
			'GM' => Yii::t('app/country', 'Gambia'),
			'GE' => Yii::t('app/country', 'Georgia'),
			'DE' => Yii::t('app/country', 'Germany'),
			'GH' => Yii::t('app/country', 'Ghana'),
			'GI' => Yii::t('app/country', 'Gibraltar'),
			'GR' => Yii::t('app/country', 'Greece'),
			'GL' => Yii::t('app/country', 'Greenland'),
			'GD' => Yii::t('app/country', 'Grenada'),
			'GP' => Yii::t('app/country', 'Guadeloupe'),
			'GU' => Yii::t('app/country', 'Guam'),
			'GT' => Yii::t('app/country', 'Guatemala'),
			'GG' => Yii::t('app/country', 'Guernsey'),
			'GN' => Yii::t('app/country', 'Guinea'),
			'GW' => Yii::t('app/country', 'Guinea-Bissau'),
			'GY' => Yii::t('app/country', 'Guyana'),
			'HT' => Yii::t('app/country', 'Haiti'),
			'HM' => Yii::t('app/country', 'Heard Island & Mcdonald Islands'),
			'VA' => Yii::t('app/country', 'Holy See (Vatican City State)'),
			'HN' => Yii::t('app/country', 'Honduras'),
			'HK' => Yii::t('app/country', 'Hong Kong'),
			'HU' => Yii::t('app/country', 'Hungary'),
			'IS' => Yii::t('app/country', 'Iceland'),
			'IN' => Yii::t('app/country', 'India'),
			'ID' => Yii::t('app/country', 'Indonesia'),
			'IR' => Yii::t('app/country', 'Iran Islamic Republic Of'),
			'IQ' => Yii::t('app/country', 'Iraq'),
			'IE' => Yii::t('app/country', 'Ireland'),
			'IM' => Yii::t('app/country', 'Isle Of Man'),
			'IL' => Yii::t('app/country', 'Israel'),
			'IT' => Yii::t('app/country', 'Italy'),
			'JM' => Yii::t('app/country', 'Jamaica'),
			'JP' => Yii::t('app/country', 'Japan'),
			'JE' => Yii::t('app/country', 'Jersey'),
			'JO' => Yii::t('app/country', 'Jordan'),
			'KZ' => Yii::t('app/country', 'Kazakhstan'),
			'KE' => Yii::t('app/country', 'Kenya'),
			'KI' => Yii::t('app/country', 'Kiribati'),
			'KR' => Yii::t('app/country', 'Korea'),
			'KW' => Yii::t('app/country', 'Kuwait'),
			'KG' => Yii::t('app/country', 'Kyrgyzstan'),
			'LA' => Yii::t('app/country', 'Lao People\'s Democratic Republic'),
			'LV' => Yii::t('app/country', 'Latvia'),
			'LB' => Yii::t('app/country', 'Lebanon'),
			'LS' => Yii::t('app/country', 'Lesotho'),
			'LR' => Yii::t('app/country', 'Liberia'),
			'LY' => Yii::t('app/country', 'Libyan Arab Jamahiriya'),
			'LI' => Yii::t('app/country', 'Liechtenstein'),
			'LT' => Yii::t('app/country', 'Lithuania'),
			'LU' => Yii::t('app/country', 'Luxembourg'),
			'MO' => Yii::t('app/country', 'Macao'),
			'MK' => Yii::t('app/country', 'Macedonia'),
			'MG' => Yii::t('app/country', 'Madagascar'),
			'MW' => Yii::t('app/country', 'Malawi'),
			'MY' => Yii::t('app/country', 'Malaysia'),
			'MV' => Yii::t('app/country', 'Maldives'),
			'ML' => Yii::t('app/country', 'Mali'),
			'MT' => Yii::t('app/country', 'Malta'),
			'MH' => Yii::t('app/country', 'Marshall Islands'),
			'MQ' => Yii::t('app/country', 'Martinique'),
			'MR' => Yii::t('app/country', 'Mauritania'),
			'MU' => Yii::t('app/country', 'Mauritius'),
			'YT' => Yii::t('app/country', 'Mayotte'),
			'MX' => Yii::t('app/country', 'Mexico'),
			'FM' => Yii::t('app/country', 'Micronesia Federated States Of'),
			'MD' => Yii::t('app/country', 'Moldova'),
			'MC' => Yii::t('app/country', 'Monaco'),
			'MN' => Yii::t('app/country', 'Mongolia'),
			'ME' => Yii::t('app/country', 'Montenegro'),
			'MS' => Yii::t('app/country', 'Montserrat'),
			'MA' => Yii::t('app/country', 'Morocco'),
			'MZ' => Yii::t('app/country', 'Mozambique'),
			'MM' => Yii::t('app/country', 'Myanmar'),
			'NA' => Yii::t('app/country', 'Namibia'),
			'NR' => Yii::t('app/country', 'Nauru'),
			'NP' => Yii::t('app/country', 'Nepal'),
			'NL' => Yii::t('app/country', 'Netherlands'),
			'AN' => Yii::t('app/country', 'Netherlands Antilles'),
			'NC' => Yii::t('app/country', 'New Caledonia'),
			'NZ' => Yii::t('app/country', 'New Zealand'),
			'NI' => Yii::t('app/country', 'Nicaragua'),
			'NE' => Yii::t('app/country', 'Niger'),
			'NG' => Yii::t('app/country', 'Nigeria'),
			'NU' => Yii::t('app/country', 'Niue'),
			'NF' => Yii::t('app/country', 'Norfolk Island'),
			'MP' => Yii::t('app/country', 'Northern Mariana Islands'),
			'NO' => Yii::t('app/country', 'Norway'),
			'OM' => Yii::t('app/country', 'Oman'),
			'PK' => Yii::t('app/country', 'Pakistan'),
			'PW' => Yii::t('app/country', 'Palau'),
			'PS' => Yii::t('app/country', 'Palestinian Territory Occupied'),
			'PA' => Yii::t('app/country', 'Panama'),
			'PG' => Yii::t('app/country', 'Papua New Guinea'),
			'PY' => Yii::t('app/country', 'Paraguay'),
			'PE' => Yii::t('app/country', 'Peru'),
			'PH' => Yii::t('app/country', 'Philippines'),
			'PN' => Yii::t('app/country', 'Pitcairn'),
			'PL' => Yii::t('app/country', 'Poland'),
			'PT' => Yii::t('app/country', 'Portugal'),
			'PR' => Yii::t('app/country', 'Puerto Rico'),
			'QA' => Yii::t('app/country', 'Qatar'),
			'RE' => Yii::t('app/country', 'Reunion'),
			'RO' => Yii::t('app/country', 'Romania'),
			'RU' => Yii::t('app/country', 'Russian Federation'),
			'RW' => Yii::t('app/country', 'Rwanda'),
			'BL' => Yii::t('app/country', 'Saint Barthelemy'),
			'SH' => Yii::t('app/country', 'Saint Helena'),
			'KN' => Yii::t('app/country', 'Saint Kitts And Nevis'),
			'LC' => Yii::t('app/country', 'Saint Lucia'),
			'MF' => Yii::t('app/country', 'Saint Martin'),
			'PM' => Yii::t('app/country', 'Saint Pierre And Miquelon'),
			'VC' => Yii::t('app/country', 'Saint Vincent And Grenadines'),
			'WS' => Yii::t('app/country', 'Samoa'),
			'SM' => Yii::t('app/country', 'San Marino'),
			'ST' => Yii::t('app/country', 'Sao Tome And Principe'),
			'SA' => Yii::t('app/country', 'Saudi Arabia'),
			'SN' => Yii::t('app/country', 'Senegal'),
			'RS' => Yii::t('app/country', 'Serbia'),
			'SC' => Yii::t('app/country', 'Seychelles'),
			'SL' => Yii::t('app/country', 'Sierra Leone'),
			'SG' => Yii::t('app/country', 'Singapore'),
			'SK' => Yii::t('app/country', 'Slovakia'),
			'SI' => Yii::t('app/country', 'Slovenia'),
			'SB' => Yii::t('app/country', 'Solomon Islands'),
			'SO' => Yii::t('app/country', 'Somalia'),
			'ZA' => Yii::t('app/country', 'South Africa'),
			'GS' => Yii::t('app/country', 'South Georgia And Sandwich Isl.'),
			'ES' => Yii::t('app/country', 'Spain'),
			'LK' => Yii::t('app/country', 'Sri Lanka'),
			'SD' => Yii::t('app/country', 'Sudan'),
			'SR' => Yii::t('app/country', 'Suriname'),
			'SJ' => Yii::t('app/country', 'Svalbard And Jan Mayen'),
			'SZ' => Yii::t('app/country', 'Swaziland'),
			'SE' => Yii::t('app/country', 'Sweden'),
			'CH' => Yii::t('app/country', 'Switzerland'),
			'SY' => Yii::t('app/country', 'Syrian Arab Republic'),
			'TW' => Yii::t('app/country', 'Taiwan'),
			'TJ' => Yii::t('app/country', 'Tajikistan'),
			'TZ' => Yii::t('app/country', 'Tanzania'),
			'TH' => Yii::t('app/country', 'Thailand'),
			'TL' => Yii::t('app/country', 'Timor-Leste'),
			'TG' => Yii::t('app/country', 'Togo'),
			'TK' => Yii::t('app/country', 'Tokelau'),
			'TO' => Yii::t('app/country', 'Tonga'),
			'TT' => Yii::t('app/country', 'Trinidad And Tobago'),
			'TN' => Yii::t('app/country', 'Tunisia'),
			'TR' => Yii::t('app/country', 'Turkey'),
			'TM' => Yii::t('app/country', 'Turkmenistan'),
			'TC' => Yii::t('app/country', 'Turks And Caicos Islands'),
			'TV' => Yii::t('app/country', 'Tuvalu'),
			'UG' => Yii::t('app/country', 'Uganda'),
			'UA' => Yii::t('app/country', 'Ukraine'),
			'AE' => Yii::t('app/country', 'United Arab Emirates'),
			'GB' => Yii::t('app/country', 'United Kingdom'),
			'US' => Yii::t('app/country', 'United States'),
			'UM' => Yii::t('app/country', 'United States Outlying Islands'),
			'UY' => Yii::t('app/country', 'Uruguay'),
			'UZ' => Yii::t('app/country', 'Uzbekistan'),
			'VU' => Yii::t('app/country', 'Vanuatu'),
			'VE' => Yii::t('app/country', 'Venezuela'),
			'VN' => Yii::t('app/country', 'Viet Nam'),
			'VG' => Yii::t('app/country', 'Virgin Islands, British'),
			'VI' => Yii::t('app/country', 'Virgin Islands, U.S.'),
			'WF' => Yii::t('app/country', 'Wallis And Futuna'),
			'EH' => Yii::t('app/country', 'Western Sahara'),
			'YE' => Yii::t('app/country', 'Yemen'),
			'ZM' => Yii::t('app/country', 'Zambia'),
			'ZW' => Yii::t('app/country', 'Zimbabwe'),
		];
	}

    protected static function iso3166_1_numeric()
    {
        return [
            'AB' => '895',
            'AU' => '036',
            'AT' => '040',
            'AZ' => '031',
            'AL' => '008',
            'DZ' => '012',
            'AS' => '016',
            'AI' => '660',
            'AO' => '024',
            'AD' => '020',
            'AQ' => '010',
            'AG' => '028',
            'AR' => '032',
            'AM' => '051',
            'AW' => '533',
            'AF' => '004',
            'BS' => '044',
            'BD' => '050',
            'BB' => '052',
            'BH' => '048',
            'BY' => '112',
            'BZ' => '084',
            'BE' => '056',
            'BJ' => '204',
            'BM' => '060',
            'BG' => '100',
            'BO' => '068',
            'BQ' => '535',
            'BA' => '070',
            'BW' => '072',
            'BR' => '076',
            'IO' => '086',
            'BN' => '096',
            'BF' => '854',
            'BI' => '108',
            'BT' => '064',
            'VU' => '548',
            'HU' => '348',
            'VE' => '862',
            'VG' => '092',
            'VI' => '850',
            'VN' => '704',
            'GA' => '266',
            'HT' => '332',
            'GY' => '328',
            'GM' => '270',
            'GH' => '288',
            'GP' => '312',
            'GT' => '320',
            'GN' => '324',
            'GW' => '624',
            'DE' => '276',
            'GG' => '831',
            'GI' => '292',
            'HN' => '340',
            'HK' => '344',
            'GD' => '308',
            'GL' => '304',
            'GR' => '300',
            'GE' => '268',
            'GU' => '316',
            'DK' => '208',
            'JE' => '832',
            'DJ' => '262',
            'DM' => '212',
            'DO' => '214',
            'EG' => '818',
            'ZM' => '894',
            'EH' => '732',
            'ZW' => '716',
            'IL' => '376',
            'IN' => '356',
            'ID' => '360',
            'JO' => '400',
            'IQ' => '368',
            'IR' => '364',
            'IE' => '372',
            'IS' => '352',
            'ES' => '724',
            'IT' => '380',
            'YE' => '887',
            'CV' => '132',
            'KZ' => '398',
            'KH' => '116',
            'CM' => '120',
            'CA' => '124',
            'QA' => '634',
            'KE' => '404',
            'CY' => '196',
            'KG' => '417',
            'KI' => '296',
            'CN' => '156',
            'CC' => '166',
            'CO' => '170',
            'KM' => '174',
            'CG' => '178',
            'CD' => '180',
            'KP' => '408',
            'KR' => '410',
            'CR' => '188',
            'CI' => '384',
            'CU' => '192',
            'KW' => '414',
            'CW' => '531',
            'LA' => '418',
            'LV' => '428',
            'LS' => '426',
            'LB' => '422',
            'LY' => '434',
            'LR' => '430',
            'LI' => '438',
            'LT' => '440',
            'LU' => '442',
            'MU' => '480',
            'MR' => '478',
            'MG' => '450',
            'YT' => '175',
            'MO' => '446',
            'MW' => '454',
            'MY' => '458',
            'ML' => '466',
            'UM' => '581',
            'MV' => '462',
            'MT' => '470',
            'MA' => '504',
            'MQ' => '474',
            'MH' => '584',
            'MX' => '484',
            'FM' => '583',
            'MZ' => '508',
            'MD' => '498',
            'MC' => '492',
            'MN' => '496',
            'MS' => '500',
            'MM' => '104',
            'NA' => '516',
            'NR' => '520',
            'NP' => '524',
            'NE' => '562',
            'NG' => '566',
            'NL' => '528',
            'NI' => '558',
            'NU' => '570',
            'NZ' => '554',
            'NC' => '540',
            'NO' => '578',
            'AE' => '784',
            'OM' => '512',
            'BV' => '074',
            'IM' => '833',
            'NF' => '574',
            'CX' => '162',
            'HM' => '334',
            'KY' => '136',
            'CK' => '184',
            'TC' => '796',
            'PK' => '586',
            'PW' => '585',
            'PS' => '275',
            'PA' => '591',
            'VA' => '336',
            'PG' => '598',
            'PY' => '600',
            'PE' => '604',
            'PN' => '612',
            'PL' => '616',
            'PT' => '620',
            'PR' => '630',
            'MK' => '807',
            'RE' => '638',
            'RU' => '643',
            'RW' => '646',
            'RO' => '642',
            'WS' => '882',
            'SM' => '674',
            'ST' => '678',
            'SA' => '682',
            'SZ' => '748',
            'SH' => '654',
            'MP' => '580',
            'BL' => '652',
            'MF' => '663',
            'SN' => '686',
            'VC' => '670',
            'LC' => '662',
            'KN' => '659',
            'PM' => '666',
            'RS' => '688',
            'SC' => '690',
            'SG' => '702',
            'SX' => '534',
            'SY' => '760',
            'SK' => '703',
            'SI' => '705',
            'GB' => '826',
            'US' => '840',
            'SB' => '090',
            'SO' => '706',
            'SD' => '736',
            'SR' => '740',
            'SL' => '694',
            'TJ' => '762',
            'TH' => '764',
            'TW' => '158',
            'TZ' => '834',
            'TL' => '626',
            'TG' => '768',
            'TK' => '772',
            'TO' => '776',
            'TT' => '780',
            'TV' => '798',
            'TN' => '788',
            'TM' => '795',
            'TR' => '792',
            'UG' => '800',
            'UZ' => '860',
            'UA' => '804',
            'WF' => '876',
            'UY' => '858',
            'FO' => '234',
            'FJ' => '242',
            'PH' => '608',
            'FI' => '246',
            'FK' => '238',
            'FR' => '250',
            'GF' => '254',
            'PF' => '258',
            'TF' => '260',
            'HR' => '191',
            'CF' => '140',
            'TD' => '148',
            'ME' => '499',
            'CZ' => '203',
            'CL' => '152',
            'CH' => '756',
            'SE' => '752',
            'SJ' => '744',
            'LK' => '144',
            'EC' => '218',
            'GQ' => '226',
            'AX' => '248',
            'SV' => '222',
            'ER' => '232',
            'EE' => '233',
            'ET' => '231',
            'ZA' => '710',
            'GS' => '239',
            'OS' => '896',
            'SS' => '728',
            'JM' => '388',
            'JP' => '392',
        ];
    }

    protected static function iso3166_1_alfa_2_byName()
    {
        return [
            'Afghanistan'                       => 'AF',
            'Aland Islands'                     => 'AX',
            'Albania'                           => 'AL',
            'Algeria'                           => 'DZ',
            'American Samoa'                    => 'AS',
            'Andorra'                           => 'AD',
            'Angola'                            => 'AO',
            'Anguilla'                          => 'AI',
            'Antarctica'                        => 'AQ',
            'Antigua And Barbuda'               => 'AG',
            'Argentina'                         => 'AR',
            'Armenia'                           => 'AM',
            'Aruba'                             => 'AW',
            'Australia'                         => 'AU',
            'Austria'                           => 'AT',
            'Azerbaijan'                        => 'AZ',
            'Bahamas'                           => 'BS',
            'Bahrain'                           => 'BH',
            'Bangladesh'                        => 'BD',
            'Barbados'                          => 'BB',
            'Belarus'                           => 'BY',
            'Belgium'                           => 'BE',
            'Belize'                            => 'BZ',
            'Benin'                             => 'BJ',
            'Bermuda'                           => 'BM',
            'Bhutan'                            => 'BT',
            'Bolivia'                           => 'BO',
            'Bosnia And Herzegovina'            => 'BA',
            'Botswana'                          => 'BW',
            'Bouvet Island'                     => 'BV',
            'Brazil'                            => 'BR',
            'British Indian Ocean Territory'    => 'IO',
            'Brunei Darussalam'                 => 'BN',
            'Bulgaria'                          => 'BG',
            'Burkina Faso'                      => 'BF',
            'Burundi'                           => 'BI',
            'Cambodia'                          => 'KH',
            'Cameroon'                          => 'CM',
            'Canada'                            => 'CA',
            'Cape Verde'                        => 'CV',
            'Cayman Islands'                    => 'KY',
            'Central African Republic'          => 'CF',
            'Chad'                              => 'TD',
            'Chile'                             => 'CL',
            'China'                             => 'CN',
            'Christmas Island'                  => 'CX',
            'Cocos (Keeling) Islands'           => 'CC',
            'Colombia'                          => 'CO',
            'Comoros'                           => 'KM',
            'Congo'                             => 'CG',
            'Congo Democratic Republic'         => 'CD',
            'Cook Islands'                      => 'CK',
            'Costa Rica'                        => 'CR',
            'Cote D\'Ivoire'                    => 'CI',
            'Croatia'                           => 'HR',
            'Cuba'                              => 'CU',
            'Cyprus'                            => 'CY',
            'Czech Republic'                    => 'CZ',
            'Denmark'                           => 'DK',
            'Djibouti'                          => 'DJ',
            'Dominica'                          => 'DM',
            'Dominican Republic'                => 'DO',
            'Ecuador'                           => 'EC',
            'Egypt'                             => 'EG',
            'El Salvador'                       => 'SV',
            'Equatorial Guinea'                 => 'GQ',
            'Eritrea'                           => 'ER',
            'Estonia'                           => 'EE',
            'Ethiopia'                          => 'ET',
            'Falkland Islands (Malvinas)'       => 'FK',
            'Faroe Islands'                     => 'FO',
            'Fiji'                              => 'FJ',
            'Finland'                           => 'FI',
            'France'                            => 'FR',
            'French Guiana'                     => 'GF',
            'French Polynesia'                  => 'PF',
            'French Southern Territories'       => 'TF',
            'Gabon'                             => 'GA',
            'Gambia'                            => 'GM',
            'Georgia'                           => 'GE',
            'Germany'                           => 'DE',
            'Ghana'                             => 'GH',
            'Gibraltar'                         => 'GI',
            'Greece'                            => 'GR',
            'Greenland'                         => 'GL',
            'Grenada'                           => 'GD',
            'Guadeloupe'                        => 'GP',
            'Guam'                              => 'GU',
            'Guatemala'                         => 'GT',
            'Guernsey'                          => 'GG',
            'Guinea'                            => 'GN',
            'Guinea-Bissau'                     => 'GW',
            'Guyana'                            => 'GY',
            'Haiti'                             => 'HT',
            'Heard Island & Mcdonald Islands'   => 'HM',
            'Holy See (Vatican City State)'     => 'VA',
            'Honduras'                          => 'HN',
            'Hong Kong'                         => 'HK',
            'Hungary'                           => 'HU',
            'Iceland'                           => 'IS',
            'India'                             => 'IN',
            'Indonesia'                         => 'ID',
            'Iran Islamic Republic Of'          => 'IR',
            'Iraq'                              => 'IQ',
            'Ireland'                           => 'IE',
            'Isle Of Man'                       => 'IM',
            'Israel'                            => 'IL',
            'Italy'                             => 'IT',
            'Jamaica'                           => 'JM',
            'Japan'                             => 'JP',
            'Jersey'                            => 'JE',
            'Jordan'                            => 'JO',
            'Kazakhstan'                        => 'KZ',
            'Kenya'                             => 'KE',
            'Kiribati'                          => 'KI',
            'Korea'                             => 'KR',
            'Kuwait'                            => 'KW',
            'Kyrgyzstan'                        => 'KG',
            'Lao People\'s Democratic Republic' => 'LA',
            'Latvia'                            => 'LV',
            'Lebanon'                           => 'LB',
            'Lesotho'                           => 'LS',
            'Liberia'                           => 'LR',
            'Libyan Arab Jamahiriya'            => 'LY',
            'Liechtenstein'                     => 'LI',
            'Lithuania'                         => 'LT',
            'Luxembourg'                        => 'LU',
            'Macao'                             => 'MO',
            'Macedonia'                         => 'MK',
            'Madagascar'                        => 'MG',
            'Malawi'                            => 'MW',
            'Malaysia'                          => 'MY',
            'Maldives'                          => 'MV',
            'Mali'                              => 'ML',
            'Malta'                             => 'MT',
            'Marshall Islands'                  => 'MH',
            'Martinique'                        => 'MQ',
            'Mauritania'                        => 'MR',
            'Mauritius'                         => 'MU',
            'Mayotte'                           => 'YT',
            'Mexico'                            => 'MX',
            'Micronesia Federated States Of'    => 'FM',
            'Moldova'                           => 'MD',
            'Monaco'                            => 'MC',
            'Mongolia'                          => 'MN',
            'Montenegro'                        => 'ME',
            'Montserrat'                        => 'MS',
            'Morocco'                           => 'MA',
            'Mozambique'                        => 'MZ',
            'Myanmar'                           => 'MM',
            'Namibia'                           => 'NA',
            'Nauru'                             => 'NR',
            'Nepal'                             => 'NP',
            'Netherlands'                       => 'NL',
            'Netherlands Antilles'              => 'AN',
            'New Caledonia'                     => 'NC',
            'New Zealand'                       => 'NZ',
            'Nicaragua'                         => 'NI',
            'Niger'                             => 'NE',
            'Nigeria'                           => 'NG',
            'Niue'                              => 'NU',
            'Norfolk Island'                    => 'NF',
            'Northern Mariana Islands'          => 'MP',
            'Norway'                            => 'NO',
            'Oman'                              => 'OM',
            'Pakistan'                          => 'PK',
            'Palau'                             => 'PW',
            'Palestinian Territory Occupied'    => 'PS',
            'Panama'                            => 'PA',
            'Papua New Guinea'                  => 'PG',
            'Paraguay'                          => 'PY',
            'Peru'                              => 'PE',
            'Philippines'                       => 'PH',
            'Pitcairn'                          => 'PN',
            'Poland'                            => 'PL',
            'Portugal'                          => 'PT',
            'Puerto Rico'                       => 'PR',
            'Qatar'                             => 'QA',
            'Reunion'                           => 'RE',
            'Romania'                           => 'RO',
            'Russian Federation'                => 'RU',
            'Russia'                            => 'RU',
            'Rwanda'                            => 'RW',
            'Saint Barthelemy'                  => 'BL',
            'Saint Helena'                      => 'SH',
            'Saint Kitts And Nevis'             => 'KN',
            'Saint Lucia'                       => 'LC',
            'Saint Martin'                      => 'MF',
            'Saint Pierre And Miquelon'         => 'PM',
            'Saint Vincent And Grenadines'      => 'VC',
            'Samoa'                             => 'WS',
            'San Marino'                        => 'SM',
            'Sao Tome And Principe'             => 'ST',
            'Saudi Arabia'                      => 'SA',
            'Senegal'                           => 'SN',
            'Serbia'                            => 'RS',
            'Seychelles'                        => 'SC',
            'Sierra Leone'                      => 'SL',
            'Singapore'                         => 'SG',
            'Slovakia'                          => 'SK',
            'Slovenia'                          => 'SI',
            'Solomon Islands'                   => 'SB',
            'Somalia'                           => 'SO',
            'South Africa'                      => 'ZA',
            'South Georgia And Sandwich Isl.'   => 'GS',
            'Spain'                             => 'ES',
            'Sri Lanka'                         => 'LK',
            'Sudan'                             => 'SD',
            'Suriname'                          => 'SR',
            'Svalbard And Jan Mayen'            => 'SJ',
            'Swaziland'                         => 'SZ',
            'Sweden'                            => 'SE',
            'Switzerland'                       => 'CH',
            'Syrian Arab Republic'              => 'SY',
            'Taiwan'                            => 'TW',
            'Tajikistan'                        => 'TJ',
            'Tanzania'                          => 'TZ',
            'Thailand'                          => 'TH',
            'Timor-Leste'                       => 'TL',
            'Togo'                              => 'TG',
            'Tokelau'                           => 'TK',
            'Tonga'                             => 'TO',
            'Trinidad And Tobago'               => 'TT',
            'Tunisia'                           => 'TN',
            'Turkey'                            => 'TR',
            'Turkmenistan'                      => 'TM',
            'Turks And Caicos Islands'          => 'TC',
            'Tuvalu'                            => 'TV',
            'Uganda'                            => 'UG',
            'Ukraine'                           => 'UA',
            'United Arab Emirates'              => 'AE',
            'United Kingdom'                    => 'GB',
            'United States'                     => 'US',
            'United States Outlying Islands'    => 'UM',
            'Uruguay'                           => 'UY',
            'Uzbekistan'                        => 'UZ',
            'Vanuatu'                           => 'VU',
            'Venezuela'                         => 'VE',
            'Viet Nam'                          => 'VN',
            'Virgin Islands, British'           => 'VG',
            'Virgin Islands, U.S.'              => 'VI',
            'Wallis And Futuna'                 => 'WF',
            'Western Sahara'                    => 'EH',
            'Yemen'                             => 'YE',
            'Zambia'                            => 'ZM',
            'Zimbabwe'                          => 'ZW',
        ];
    }

	/**
	 * Функция возвращает коды стран для тестовых терминалов.
	 * Необходимы для тестового обмена.
	 */
	protected static function testTerminalCountryCodes()
	{
		if (YII_ENV_DEV) {
			return [
				'XX' => Yii::t('app/country', 'XX terminal test country'),
				'ZZ' => Yii::t('app/country', 'ZZ terminal test country'),
			];
		} else {
			return [];
		}
	}

	/**
	 * Функция возвращает список всех стран, включая тестовые
	 * @return array
	 */
	protected static function getAllCountryCodes()
	{
		if (is_null(self::$allCountryCodes)) {
			self::$allCountryCodes = \yii\helpers\ArrayHelper::merge(
							self::iso3166_1_alfa_2(), self::testTerminalCountryCodes());
		}

        return self::$allCountryCodes;
	}

    protected static function getAllNumericCodes()
    {
        if (self::$allNumericCodes == null) {
            self::$allNumericCodes = self::iso3166_1_numeric();
        }

        return self::$allNumericCodes;
    }

	/**
	 * @param int $type
	 * @return array
	 */
	public static function getCodes($type = self::ISO_3166_1_ALFA_2)
	{
		return array_keys(self::getAllCountryCodes());
	}

	/**
	 * @param $code
	 * @param int $type
	 * @return string|null
	 */
	public static function getName($code, $type = self::ISO_3166_1_ALFA_2)
	{
		$allCountries = self::getAllCountryCodes();

		return array_key_exists($code, $allCountries) ? $allCountries[$code] : '';
	}

    public static function getNumericCode($alfa2Code)
    {
        $allNumericCodes = self::iso3166_1_numeric();

        return array_key_exists($alfa2Code, $allNumericCodes) ? $allNumericCodes[$alfa2Code] : null;
    }

    public static function getAlfaCode($numericCode)
    {
        $alfaByNumeric = array_flip(static::iso3166_1_numeric());

        return array_key_exists($numericCode, $alfaByNumeric) ? $alfaByNumeric[$numericCode] : null;
    }

    public static function getIso3166_1_alfa_2CodeByName($name)
    {
        $map = static::iso3166_1_alfa_2_byName();
        foreach ($map as $key => $code) {
            if (strtolower($key) === strtolower($name)) {
                return $code;
            }
        }

        return null;
    }

    public static function getLatinNameByIso3166_1_numeric($numericCode)
    {
        $alfaByNumeric = array_flip(static::iso3166_1_numeric());
        if (!array_key_exists($numericCode, $alfaByNumeric)) {
            return null;
        }
        $alfaCode = $alfaByNumeric[$numericCode];

        $nameByAlfa = array_flip(static::iso3166_1_alfa_2_byName());

        return array_key_exists($alfaCode, $nameByAlfa) ? $nameByAlfa[$alfaCode] : null;
    }

    public static function getAll()
    {
        $alfaToName = static::iso3166_1_alfa_2();
        $alfaToNumeric = static::iso3166_1_numeric();

        return array_map(
            function ($alfaCode) use ($alfaToNumeric, $alfaToName) {
                return [
                    'alfaCode' => $alfaCode,
                    'name' => $alfaToName[$alfaCode],
                    'numericCode' => $alfaToNumeric[$alfaCode] ?? null,
                ];
            },
            array_keys($alfaToName)
        );
    }

    public static function getNameByNumericCode($numericCode, $attachCode = false)
    {
        $numericToAlfa = array_flip(static::iso3166_1_numeric());
        if (!array_key_exists($numericCode, $numericToAlfa)) {
            return $attachCode ? $numericCode : null;
        }
        $alfaCode = $numericToAlfa[$numericCode];
        $alfaToName = static::iso3166_1_alfa_2();

        if (!$alfaToName) {
            return $attachCode ? $numericCode : null;
        }

        $name = $alfaToName[$alfaCode];

        return $attachCode
                ? $name . ' (' . $numericCode . ')'
                : $name;
    }

}
