<?php
/**
 * FailReason
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FINTECH
 *
 * Документация FINTECH REST API
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace common\models\sbbol2;

use ArrayAccess;

/**
 * FailReason Class Doc Comment
 *
 * @category Class
 * @description Причина отказа
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class FailReason implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'FailReason';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'docField' => 'string',
        'reasonComment' => 'string',
        'reasonId' => 'string',
        'returnComment' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'docField' => null,
        'reasonComment' => null,
        'reasonId' => null,
        'returnComment' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'docField' => 'docField',
        'reasonComment' => 'reasonComment',
        'reasonId' => 'reasonId',
        'returnComment' => 'returnComment',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'docField' => 'setDocField',
        'reasonComment' => 'setReasonComment',
        'reasonId' => 'setReasonId',
        'returnComment' => 'setReturnComment',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'docField' => 'getDocField',
        'reasonComment' => 'getReasonComment',
        'reasonId' => 'getReasonId',
        'returnComment' => 'getReturnComment',
    ];

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['docField'] = isset($data['docField']) ? $data['docField'] : null;
        $this->container['reasonComment'] = isset($data['reasonComment']) ? $data['reasonComment'] : null;
        $this->container['reasonId'] = isset($data['reasonId']) ? $data['reasonId'] : null;
        $this->container['returnComment'] = isset($data['returnComment']) ? $data['returnComment'] : null;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets docField
     *
     * @return string
     */
    public function getDocField()
    {
        return $this->container['docField'];
    }

    /**
     * Sets docField
     *
     * @param string $docField Поле документа
     *
     * @return $this
     */
    public function setDocField($docField)
    {
        $this->container['docField'] = $docField;

        return $this;
    }

    /**
     * Gets reasonComment
     *
     * @return string
     */
    public function getReasonComment()
    {
        return $this->container['reasonComment'];
    }

    /**
     * Sets reasonComment
     *
     * @param string $reasonComment Правило заполнения/замечания
     *
     * @return $this
     */
    public function setReasonComment($reasonComment)
    {
        $this->container['reasonComment'] = $reasonComment;

        return $this;
    }

    /**
     * Gets reasonId
     *
     * @return string
     */
    public function getReasonId()
    {
        return $this->container['reasonId'];
    }

    /**
     * Sets reasonId
     *
     * @param string $reasonId Код причины отказа
     *
     * @return $this
     */
    public function setReasonId($reasonId)
    {
        $this->container['reasonId'] = $reasonId;

        return $this;
    }

    /**
     * Gets returnComment
     *
     * @return string
     */
    public function getReturnComment()
    {
        return $this->container['returnComment'];
    }

    /**
     * Sets returnComment
     *
     * @param string $returnComment Комментарий
     *
     * @return $this
     */
    public function setReturnComment($returnComment)
    {
        $this->container['returnComment'] = $returnComment;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int   $offset Offset
     * @param mixed $value  Value to be set
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
