common\models\sbbolxml\response\ResponseType\DocTypeConfigsAType:
    properties:
        docTypeConfig:
            expose: true
            access_type: public_method
            serialized_name: DocTypeConfig
            xml_element:
                namespace: 'http://bssys.com/upg/response'
            accessor:
                getter: getDocTypeConfig
                setter: setDocTypeConfig
            xml_list:
                inline: true
                entry_name: DocTypeConfig
                namespace: 'http://bssys.com/upg/response'
            type: array<common\models\sbbolxml\response\DocTypeConfigType>
