common\models\sbbolxml\response\ResponseType\OrgSettingsAType\OrgUPGLogsRequestsAType:
    properties:
        orgUPGLogsRequest:
            expose: true
            access_type: public_method
            serialized_name: OrgUPGLogsRequest
            xml_element:
                namespace: 'http://bssys.com/upg/response'
            accessor:
                getter: getOrgUPGLogsRequest
                setter: setOrgUPGLogsRequest
            type: common\models\sbbolxml\response\OrgUPGLogsRequestType
