<?php
return [
    'user' => [
        'type' => 1,
        'ruleName' => 'roleGroup',
        'children' => [
            'accessService',
            'documentView',
            'pageView',
            'commonDocument',
            'commonApprove',
            'commonEventlog',
            'commonMyKeysCertificates',
            'commonStatistic',
            'commonHelp',
            'commonParticipants',
            'documentCreate',
            'documentDelete',
            'documentSign',
            'commonCertificates',
            'commonCertificatesStatusManagement',
            'pageManage',
            'documentImportErrors',
            'vtbDocuments',
            'documentVtbDocuments',
        ],
    ],
    'admin' => [
        'type' => 1,
        'ruleName' => 'roleGroup',
        'children' => [
            'accessService',
            'documentView',
            'documentDelete',
            'documentManage',
            'pageView',
            'pageManage',
            'commonDocument',
            'commonDocumentAdmin',
            'commonSettings',
            'commonReport',
            'commonApprove',
            'commonUsers',
            'commonEventlog',
            'commonCertificates',
            'commonParticipants',
            'commonTour',
            'commonStatistic',
            'commonHelp',
            'commonCertificatesStatusManagement',
            'commonAccessMainAdmin',
            'documentImportErrors',
            'commonAdmins',
        ],
    ],
    'controller' => [
        'type' => 1,
        'ruleName' => 'roleGroup',
        'children' => [
            'accessService',
            'documentView',
            'documentControllerVerification',
            'pageView',
            'commonDocumentAdmin',
        ],
    ],
    'lso' => [
        'type' => 1,
        'ruleName' => 'roleGroup',
        'children' => [
            'accessService',
            'documentView',
            'pageView',
            'commonUsers',
            'commonEventlog',
            'commonStatistic',
            'actionAccept',
        ],
    ],
    'rso' => [
        'type' => 1,
        'ruleName' => 'roleGroup',
        'children' => [
            'accessService',
            'documentView',
            'pageView',
            'commonUsers',
            'commonEventlog',
            'commonStatistic',
            'actionAccept',
        ],
    ],
    'accessService' => [
        'type' => 2,
        'description' => 'Access to addon',
        'ruleName' => 'canAccessService',
    ],
    'documentView' => [
        'type' => 2,
        'description' => 'Document view',
        'ruleName' => 'documentViewRule',
    ],
    'documentCreate' => [
        'type' => 2,
        'description' => 'Document create',
        'ruleName' => 'documentCreateRule',
    ],
    'documentDelete' => [
        'type' => 2,
        'description' => 'Document delete',
        'ruleName' => 'documentDeleteRule',
    ],
    'documentSign' => [
        'type' => 2,
        'description' => 'Document sign',
        'ruleName' => 'documentSignRule',
    ],
    'documentManage' => [
        'type' => 2,
        'description' => 'Document control',
    ],
    'documentControllerVerification' => [
        'type' => 2,
        'description' => 'Documents for controller verification',
    ],
    'pageView' => [
        'type' => 2,
        'description' => 'Wiki page view',
    ],
    'pageManage' => [
        'type' => 2,
        'description' => 'Document delete',
        'ruleName' => 'pageManagementRule',
    ],
    'commonDocument' => [
        'type' => 2,
        'description' => 'Documents for all',
    ],
    'commonDocumentAdmin' => [
        'type' => 2,
        'description' => 'Documents for menu',
    ],
    'commonSettings' => [
        'type' => 2,
        'description' => 'System settings',
    ],
    'commonReport' => [
        'type' => 2,
        'description' => 'System report',
    ],
    'commonApprove' => [
        'type' => 2,
        'description' => 'Approve',
    ],
    'commonUsers' => [
        'type' => 2,
        'description' => 'System users',
    ],
    'commonEventlog' => [
        'type' => 2,
        'description' => 'Transport document log',
    ],
    'commonCertificates' => [
        'type' => 2,
        'description' => 'Certificates',
        'ruleName' => 'certViewPermissionRule',
    ],
    'commonParticipants' => [
        'type' => 2,
        'description' => 'Participants',
    ],
    'commonMyKeysCertificates' => [
        'type' => 2,
        'description' => 'My keys and certificates',
    ],
    'commonTour' => [
        'type' => 2,
        'description' => 'First start system tour',
    ],
    'commonStatistic' => [
        'type' => 2,
        'description' => 'Statistics page',
    ],
    'commonHelp' => [
        'type' => 2,
        'description' => 'Help',
    ],
    'actionAccept' => [
        'type' => 2,
        'description' => 'Command accepting',
    ],
    'commonCertificatesStatusManagement' => [
        'type' => 2,
        'description' => 'Manage certificates status',
        'ruleName' => 'certStatusManagementRule',
    ],
    'commonAccessMainAdmin' => [
        'type' => 2,
        'description' => 'Main admin access',
        'ruleName' => 'mainAdminRule',
    ],
    'documentImportErrors' => [
        'type' => 2,
        'description' => 'Document delete',
        'ruleName' => 'importErrorsRule',
    ],
    'commonAdmins' => [
        'type' => 2,
        'description' => 'All admins access',
    ],
    'additionalAdmin' => [
        'type' => 1,
        'ruleName' => 'roleGroup',
        'children' => [
            'accessService',
            'documentView',
            'documentDelete',
            'documentManage',
            'pageView',
            'pageManage',
            'commonDocument',
            'commonDocumentAdmin',
            'commonAccessMainAdmin',
            'commonSettings',
            'commonReport',
            'commonApprove',
            'commonUsers',
            'commonEventlog',
            'commonCertificates',
            'commonCertificatesStatusManagement',
            'commonParticipants',
            'commonTour',
            'commonStatistic',
            'commonHelp',
            'commonAdmins',
        ],
    ],
    'vtbDocuments' => [
        'type' => 2,
        'description' => 'Access VTB documents',
        'ruleName' => 'vtbDocumentsRule',
    ],
    'documentVtbDocuments' => [
        'type' => 2,
        'description' => 'Access VTB documents',
        'ruleName' => 'vtbDocumentsRule',
    ],
];
