<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detaild description for each parameter.
 */
return [
    'color' => null,
    'interactive' => true,
    'sourcePath' => '@common/modules/wiki',
    'messagePath' => '@common/modules/wiki/messages',
    'languages' => ['ru', 'en'],
    'translator' => ['WikiModule::t', 'Yii::t'],
    'sort' => true,
    'overwrite' => true,
    'removeUnused' => true,
//    'markUnused' => true,
    'except' => [
        '.git',
        '.gitignore',
        '.gitkeep',
        '/messages',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'php',
    'ignoreCategories' => ['app'],
];
